name: 유닛 테스트 및 타입 체크

on:
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-22.04

    # 레포지토리 체크아웃
    steps:
      - uses: actions/checkout@v4

      # pnpm 설치
      - name: Install pnpm 10
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      # 의존성 설치
      - name: Install dependencies
        run: pnpm install

      - name: Type check
        run: pnpm exec tsc --noEmit --skipLibCheck

      # 테스트 실행
      - name: Run tests
        run: pnpm test
